name: Android Build

on:
  release:
    types: [created]

env:
  NDK_VERSION: r27c

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: aarch64-linux-android, x86_64-linux-android

    - name: Install Android NDK
      id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: ${{ env.NDK_VERSION }}
        add-to-path: false

    - name: Configure Cargo for Android
      run: |
        mkdir -p .cargo
        cat > .cargo/config.toml << 'EOF'
        [target.aarch64-linux-android]
        linker = "${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang"

        [target.x86_64-linux-android]
        linker = "${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android26-clang"
        EOF

    - name: Build aarch64 binary
      run: |
        cargo build --target aarch64-linux-android --example sample-litmus-server
        cargo build --target aarch64-linux-android --example sample-litmus-server --release

    - name: Build x86_64 binary
      run: |
        cargo build --target x86_64-linux-android --example sample-litmus-server
        cargo build --target x86_64-linux-android --example sample-litmus-server --release

    - name: Rename binaries
      run: |
        mv target/aarch64-linux-android/debug/examples/sample-litmus-server ./webdav-server-debug-aarch64
        mv target/aarch64-linux-android/release/examples/sample-litmus-server ./webdav-server-release-aarch64
        mv target/x86_64-linux-android/debug/examples/sample-litmus-server ./webdav-server-debug-x86_64
        mv target/x86_64-linux-android/release/examples/sample-litmus-server ./webdav-server-release-x86_64

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          webdav-server-debug-aarch64
          webdav-server-debug-x86_64
          webdav-server-release-aarch64
          webdav-server-release-x86_64
